### PR TITLE
Replaced deprecated werkzeug.urls.url_quote() with urllib.parse.quote()

### LINKED ISSUE #70: Werkzeug 3.0.x support
Currently, Werkzeug 3.0.x isn't compatible with flask-openid.

```python
File "venv/lib/python3.11/site-packages/flask_openid.py", line 23, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' 
```

it's a pretty simple fix from here: https://werkzeug.palletsprojects.com/en/2.3.x/urls/

replace the single `url_quote()` call with `urllib.parse.quote()` on `flask_openid.py`.

I can submit a PR if you prefer me to do so :)

### PR DESCRIPTION
**Pull request by TheZoc**
Fixes #70

### CODE REVIEW

**Comment by frantisekz** [comment]
Backported to Fedora downstream, works fine, thanks!

**Comment by JonathanBrenner** [comment]
Would love to see this fix integrated!

**Comment by TheZoc** [comment]
Small nudge in here, hoping a maintainer takes a look at this :)

**Comment by potiuk** [comment]
I have completely forgot that I've been added as maintainer here to be able to make such releases. @TheZoc - can you please also add urllib as dependency in setup.py (install_requires?). I think I can make a release of it right after.

**Comment by potiuk** [comment]
(sorry - I've been added as maintainer to remove some very old setup2to3 dependencies only and I have not been paying attention to it @TheZoc ).

**Comment by TheZoc** [comment]
Hi @potiuk, glad to hear back from you!
I believe it's not necessary to change setup.py, since urllib is part of Python since v3.3

Please let me know if it needs any additional changes :)

**Comment by potiuk** [comment]
> I believe it's not necessary to change setup.py, since urllib is part of Python since v3.3

Right 🤦 . Somehow I thought it's requests :)

**Comment by potiuk** [comment]
BTW. Note that OpenID is a very old protocol (it's not OpenID-connect) and almost nothing supports it, and it has some known security vulnerabilities. So not sure why you need it..

**Comment by potiuk** [comment]
Released it https://pypi.org/project/Flask-OpenID/1.3.1/ - let me know if that fixed your issue.

**Pull request merged**
